### ISSUE TITLE
Update Dockerfile to work with 0.36

### ISSUE THREAD

**Issue by underyx** [returntocorp/sgrep-action#144]
Seems like we'll need more changes than usual as according to https://github.com/returntocorp/semgrep/issues/2054#issuecomment-754678088 the `PRECOMPILED_LOCATION` var we use no longer exists.

**Comment by mschwager** [comment]
Looks like `PRECOMPILED_LOCATION` has been gone since https://github.com/returntocorp/semgrep/commit/4e97e83426b6097f2a071294a5064975e7a62163, which was included in the `v0.31.0` release. Unless there's a specific reason for avoiding the binaries in the package I believe we simply remove the `PRECOMPILED_LOCATION` variable.

Is there a reason we were pulling the binaries from a separate Docker image rather than the Python package? If we can remove the `PRECOMPILED_LOCATION` I suspect we can remove the `COPY --from=semgrep /usr/local/bin/semgrep-core /tmp/semgrep-core` and `FROM returntocorp/semgrep:0.35.0@sha256:... AS semgrep` from the Dockerfile as well.

**Comment by underyx** [comment]
> Is there a reason we were pulling the binaries from a separate Docker image rather than the Python package?

The python binaries don't work on alpine.

**Comment by mschwager** [comment]
Oh I see, it's because we're using Alpine. We could probably make our lives a lot easier by using `python:3.7-slim` instead of `python:3.7-alpine`. Regardless, I wonder how its continued with work without `PRECOMPILED_LOCATION` :man_shrugging:

**Comment by mschwager** [comment]
From @mjambon:

> the ocaml executables (semgrep-core and spacegrep) are compiled statically for linux but only "partially statically" for darwin i.e. only the libc is dynamically linked but the third-party libraries that we use are linked in statically.

I believe this means we can in fact simplify things by removing the `PRECOMPILED_LOCATION`, `COPY --from=semgrep`, and `FROM ... AS semgrep` from https://github.com/returntocorp/semgrep-action/blob/develop/Dockerfile.

cc @chmccreery who could do this with the `v0.36.0` update, or we could do this separately.

**Comment by chmccreery** [comment]
@mschwager let's do this separately. Let me know if you want to do it before this release, or if we can do it later this week.

**Comment by brendongo** [comment]
I think it's continued to work without PRECOMPILED_LOCATION because pipx install semgrep just works as expected comes with the spacegrep and semgrep binaries.

**Comment by mschwager** [comment]
Fixed by https://github.com/returntocorp/semgrep-action/pull/156.
