### ISSUE TITLE
How are submodules handled?

### ISSUE THREAD

**Issue by Sjord** [returntocorp/sgrep-action#177]
I have a project with several submodules, and I want to scan the submodules using semgrep and get a diff with the baseline ref.

The TargetFileManager [contains some logic to handle submodules](https://github.com/returntocorp/semgrep-action/blob/develop/src/semgrep_agent/targets.py#L173-L186), but then when doing the diff it [explicitly ignores submodules](https://github.com/returntocorp/semgrep-action/blob/develop/src/semgrep_agent/targets.py#L108). What is the expected behaviour for submodules?

**Comment by underyx** [comment]
The current behavior is to completely ignore submodules. In fact, the code from the first link you posted is also there to ignore submodules, and it prints out some lines warning that it's doing so.

This was an intentional design decision to stop Semgrep CI from blocking CI when a submodule, which you might have no control over, has new issues, especially if the app has stricter rules than the submodule needs. We also wanted to avoid one submodule triggering tens or hundreds of security notifications as the update propagates across a large organization's repositories. Our current recommendation is to set up Semgrep with appropriate rules/policies for each submodule repository separately, to catch issues at the source.

Is this a possibility for you? Our opinion on this is loosely held, so we are open to revisiting this decision.

**Comment by Sjord** [comment]
Thank you. My use case is that I want to know when someone updates the submodule and the new version contains security issues that the old version didn't have. However, it's easily solved. I just `cd` into the submodule directory and run semgrep-action there.
