### ISSUE TITLE
Generated SARIF output not validating against JSON schema

### ISSUE THREAD

**Issue by pierre-ernst** [returntocorp/sgrep-action#243]
While generating sarif output with Semgrep action, I've noticed an extra `invocations` property that doesn't belong to the schema:
```
{
  "$schema": "https://raw.githubusercontent.com/oasis-tcs/sarif-spec/master/Schemata/sarif-schema-2.1.0.json",
  "invocations": [
    {
      "toolExecutionNotifications": []
    }
  ],
...
}
```

Note that Semgrep CLI does *not* exhibit the same behavior

**Comment by dlukeomalley** [comment]
@pierre-ernst I know we've made improvements here and I'm wondering if this behavior is still exhibited. Do you have a command you're running that I can use to reproduce?

**Comment by pierre-ernst** [comment]
Hi @dlukeomalley, I was using your GitHub action first and then upload the generated SARIF to GitHub code scanning, you can see on [this line of code](https://github.com/pierre-ernst/detect-secrets-test-data/blob/main/.github/workflows/run-semgrep-baseline.yml#L28), how a tweak is necessary.

**Comment by brendongo** [comment]
This was fixed in https://github.com/returntocorp/semgrep/releases/tag/v0.46.0 on Apr 8. Thanks for the report @pierre-ernst sorry for delay in getting back to this issue. We are now compliant with invocations property in https://docs.oasis-open.org/sarif/sarif/v2.1.0/csprd01/sarif-v2.1.0-csprd01.html#_Toc10540933
