### ISSUE TITLE
Relative paths not working

### ISSUE THREAD

**Issue by ristomcgehee** [returntocorp/sgrep-action#550]
We use Semgrep CI to scan a list of files. It's been working great for a while, but last night it failed because it no longer recognized relative file paths. This was the error: 
```
WARNING: unable to find a config; path `rules.yml` does not exist (since you are running in docker, you cannot specify arbitrary paths on the host; they must be mounted into the container)
```
Let me describe a scenario that illustrates the issue. Suppose that on my host machine, I have a path `/repo` that contains 2 files: `rules.yml` and `someFile.php`. Running with the image that has the current `v1` tag fails:
```
docker run -v /repo:/repo -w /repo --entrypoint semgrep returntocorp/semgrep-agent@sha256:9c180f736966c7649e77cbfb8bc91f42e452186e60a8c87e90dfad3f70ecbc07 --config rules.yml someFile.php
```
However, running with an older image succeeds:
```sh
docker run -v /repo:/repo -w /repo --entrypoint semgrep returntocorp/semgrep-agent@sha256:11c4bce3e5fc0fc66958d4f9e3f953664da5d65dea7d69fba4f284efaf71a428 --config rules.yml someFile.php
```
If I were to instead run the current `v1` image and specify absolute paths, then it succeeds:
```
docker run -v /repo:/repo -w /repo --entrypoint semgrep returntocorp/semgrep-agent@sha256:9c180f736966c7649e77cbfb8bc91f42e452186e60a8c87e90dfad3f70ecbc07 --config /repo/rules.yml /repo/someFile.php
```

**Comment by underyx** [comment]
Thank you @chrismcgehee for reporting this issue! We'll be taking a look at it first thing tomorrow PST morning. I'm sure it won't take long to fix as your reproduction steps seem great.

I wanted to warn you that we scheduled an update of the p/secrets ruleset for tomorrow PST morning, which will not be compatible with older versions of semgrep. (The p/secrets ruleset will use string entropy calculation features that we added in semgrep 0.83). If you pin the agent to an older version and use this ruleset, you'll start seeing failures tomorrow. So in this case I'd like to ask you to use the workaround of specifying the absolute path, instead of pinning the Docker image. Thanks!

**Comment by brendongo** [comment]
Hey @chrismcgehee if you change the target volume from /repo to /src as in instructions https://github.com/returntocorp/semgrep-action#usage-outside-ci relative paths should work for both versions: 

```
 docker run -v $(pwd):/src -w /src --entrypoint semgrep returntocorp/semgrep-agent:v1 --config rules.yml someFile.php
```

If you are using the semgrep binary and not semgrep-agent I recommend using the returntocorp/semgrep image instead of semgrep-agent

Under the hood semgrep in docker changes it's working directory to /src so that relative paths work. Looking into why the target working directory didn't affect the old version.

**Comment by brendongo** [comment]
Marking this as closed. IMO using /src instead of /repo seems fine
